Repository robocupjunioraustralia/RCJA_Registration_System, pull requests merged in 2023-09, with the labels that each got.

#538 Bump Django to 4.2.4
  Dockerfile
  Dockerfile.development
  rcjaRegistration/common/admin.py
  rcjaRegistration/coordination/tests/test_permissionUtilsUnitTests.py
  rcjaRegistration/eventfiles/urls.py
  rcjaRegistration/events/models.py
  rcjaRegistration/events/urls.py
  rcjaRegistration/invoices/urls.py
  rcjaRegistration/publicapi/urls.py
  rcjaRegistration/rcjaRegistration/settings.py
  rcjaRegistration/rcjaRegistration/settings_test.py
  rcjaRegistration/rcjaRegistration/urls.py
  rcjaRegistration/regions/models.py
  rcjaRegistration/schools/admin.py
  rcjaRegistration/schools/views.py
  rcjaRegistration/teams/tests/tests_legacy.py
  rcjaRegistration/teams/views.py
  rcjaRegistration/templates/common/loggedInbase.html
  rcjaRegistration/templates/registration/profile.html
  rcjaRegistration/templates/schools/campusForm.html
  rcjaRegistration/templates/schools/createSchool.html
  rcjaRegistration/templates/schools/schoolDetails.html
  rcjaRegistration/templates/teams/createEditTeam.html
  rcjaRegistration/templates/teams/studentForm.html
  rcjaRegistration/users/admin.py
  rcjaRegistration/users/management/commands/herokuinit.py
  rcjaRegistration/users/models.py
  rcjaRegistration/users/views.py
  requirements.txt
Labels: dependencies

#604 Add tests
  rcjaRegistration/common/tests/test_redirectsMiddleware.py
  rcjaRegistration/publicapi/tests.py
  rcjaRegistration/rcjaRegistration/settings_test.py
Labels: tests

#623 Add team creation date to admin table/export
  rcjaRegistration/teams/admin.py
Labels: enhancement

#629 Duplicate teams
  rcjaRegistration/events/migrations/0020_baseeventattendance_copiedfrom.py
  rcjaRegistration/events/models.py
  rcjaRegistration/teams/urls.py
  rcjaRegistration/teams/views.py
  rcjaRegistration/templates/events/details.html
  rcjaRegistration/templates/teams/copyTeamsList.html
Labels: feature
